### ISSUE TITLE
process move constructor implicitly deleted

### ISSUE THREAD

**Issue by bmcdanie** [eao197/procyy#2]
process move constructor is marked explicitly defaulted, but is deleted - probably due to problems with members' move constructors. I refactored my code around it, so I'm not waiting for a fix, just FYI. this problem also occurs in the original `procxx`.

**Comment by eao197** [comment]
Thanks for reporting this! We have never used `process` with move operations so this issue was hidden for a long time.

I've changed the implementation of `process` class. Now it uses PImpl idiom, which makes move constructor/operator available for `process` instances.

**Comment by bmcdanie** [comment]
excellent, thank you!
