### ISSUE TITLE
Constructor for process from vector<string>

### ISSUE THREAD

**Issue by br101** [eao197/procyy#3]
Hi! Not really an issue, but I was wondering how I could construct a process from a vector<string>, or possibly even a space separated command string ("eg. ping 8.8.8.8 -c 5"). Finally I resorted to the following but I assume there must be a better way:

	vector<string> vec; // then split the space separated cmd string into it

	procyy::process shell{vec.at(0)};
	for (size_t i = 1; i < vec.size(); i++) {
		shell.add_argument(vec[i]);
	}

**Comment by eao197** [comment]
Hi, br101!

You found the right way and there is no other method to initialize an instance of `process` for your use-case.

BTW, if you don't need to store parsed values after initializing a `process` variable you can move those values:
```cpp
vector<string> vec; // then split the space separated cmd string into it

procyy::process shell{std::move(vec.at(0))};
for (size_t i = 1; i < vec.size(); i++) {
	shell.add_argument(std::move(vec[i]));
}
```

**Comment by br101** [comment]
Okay, thank you!
